### ISSUE TITLE
浏览器打开显示文件路径

### ISSUE THREAD

**Issue by devadapter** [YooLc/docker-univpn#1]
按照readme编译镜像

```
docker build -t docker-novnc-univpn .

docker run -d \
  --name univpn \
  -p 18080:8080 \
  -p 2222:2222 \
  -e REMOTE_HOST=Remote:8080 \
  --device /dev/net/tun \
  --cap-add NET_ADMIN \
  docker-novnc-univpn
```
浏览器打开后如图
![image](https://github.com/user-attachments/assets/7e719dda-c83f-4a9c-9a79-9de7941fc56e)

这是docker logs
![image](https://github.com/user-attachments/assets/23357c03-290b-4900-a02e-7ed68e2823c3)

**Comment by YooLc** [comment]
需要打开 vnc.html 才能看到远程桌面，比如 http://localhost:18080/vnc.html

**Comment by devadapter** [comment]
非常感谢，按照您说的方式登录vpn成功，我在宿主机上要如何使用它，有使用文档吗。

**Comment by YooLc** [comment]
> 非常感谢，按照您说的方式登录vpn成功，我在宿主机上要如何使用它，有使用文档吗。

配置好后，docker 容器的 2222 端口就相当于访问 vpn 中的远程主机

如果 docker 的网络是 host 模式，可以 ssh username@127.0.0.1 -p 2222 访问 vpn 中的远程主机
